#!/usr/bin/env python3
"""Build deck.html from deck.src.html.

The deck goes on a projector in a room whose wifi is somebody else's problem, so
the shipped file carries everything it needs: both Geist variable fonts inlined
as base64, and the /try QR as an SVG path rather than a script that draws one.
`deck.src.html` stays readable and works over the network; `deck.html` is the one
you present.

Google's Geist subsets do not declare U+20B9, so the rupee sign on every slide
would fall back to a system face. The variable fonts from the `geist` npm package
do carry it, which is why they are fetched from jsdelivr instead.

    python3 pitch/build.py            # fetch what is missing, write deck.html
    python3 pitch/build.py --check    # verify deck.html is current, write nothing

Fetched fonts are cached in pitch/.fonts/ so a rebuild needs no network.
"""

from __future__ import annotations

import argparse
import base64
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "deck.src.html"
OUT = HERE / "deck.html"
CACHE = HERE / ".fonts"

TRY_URL = "https://mandate-gateway-214049084577.asia-south1.run.app/try"

FONTS = {
    "Geist": (
        "https://cdn.jsdelivr.net/npm/geist@1.3.1/dist/fonts/geist-sans/Geist-Variable.woff2",
        "Geist-Variable.woff2",
    ),
    "Geist Mono": (
        "https://cdn.jsdelivr.net/npm/geist@1.3.1/dist/fonts/geist-mono/GeistMono-Variable.woff2",
        "GeistMono-Variable.woff2",
    ),
}


def font_css() -> str:
    """Both families as one @font-face each, base64, weight 100-900 variable."""
    CACHE.mkdir(exist_ok=True)
    faces = []
    for family, (url, name) in FONTS.items():
        path = CACHE / name
        if not path.exists():
            print(f"  fetching {name}", file=sys.stderr)
            with urllib.request.urlopen(url, timeout=30) as r:
                path.write_bytes(r.read())
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        faces.append(
            f"@font-face{{font-family:'{family}';font-style:normal;"
            f"font-weight:100 900;font-display:block;"
            f"src:url(data:font/woff2;base64,{b64}) format('woff2-variations')}}"
        )
    return "<style>\n" + "\n".join(faces) + "\n</style>"


def qr_svg(url: str) -> str:
    """The /try QR as a single path. Horizontal runs are merged into one rect each.

    Rendered from this same run-merging, the result decodes back to `url` under
    OpenCV's detector, which is the only check that matters for something a judge
    points a phone at.
    """
    try:
        import segno
    except ImportError:
        sys.exit(
            "segno is required to build the QR: pip install segno\n"
            "(deck.html already in the tree keeps its QR if you skip the build)"
        )

    matrix = [list(row) for row in segno.make(url, error="m").matrix]
    n = len(matrix)
    runs = []
    for y in range(n):
        x = 0
        while x < n:
            if matrix[y][x]:
                start = x
                while x < n and matrix[y][x]:
                    x += 1
                runs.append(f"M{start} {y}h{x - start}v1h{-(x - start)}z")
            else:
                x += 1

    quiet = 2
    box = n + quiet * 2
    return (
        f'<svg viewBox="0 0 {box} {box}" role="img" '
        f'aria-label="QR code to the live attack console">'
        f'<rect width="{box}" height="{box}" fill="#fff"/>'
        f'<g transform="translate({quiet} {quiet})">'
        f'<path d="{"".join(runs)}" fill="currentColor"/></g></svg>'
    )


def build() -> str:
    html = SRC.read_text()
    if "<!--FONTS-->" not in html or "<!--QR_SVG-->" not in html:
        sys.exit("deck.src.html is missing a <!--FONTS--> or <!--QR_SVG--> placeholder")
    html = html.replace("<!--FONTS-->", font_css())
    html = html.replace("<!--QR_SVG-->", qr_svg(TRY_URL))
    return html.replace(
        "<title>Mandate — pitch deck</title>",
        "<title>Mandate — pitch deck</title>\n<!-- Generated by pitch/build.py. Edit deck.src.html. -->",
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify deck.html is current")
    args = ap.parse_args()

    html = build()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != html:
            print("deck.html is stale: run python3 pitch/build.py", file=sys.stderr)
            return 1
        print("deck.html is current")
        return 0

    OUT.write_text(html)
    print(f"wrote {OUT.relative_to(HERE.parent)}  ({len(html) / 1024:.0f} KB, no network needed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
